import os
import sys
import glob
import pandas as pd
import numpy as np

# =========================================================
# CONFIG
# =========================================================

DISEASES = ["CAD_d", "HT_d", "STR_d", "T2D_d"]

TRANSLATION = {
    "CAD_d": "CAD",
    "HT_d": "HT",
    "STR_d": "STR",
    "T2D_d": "T2D"
}

# =========================================================
# FUNCTIONS
# =========================================================

def load_pairwise_files(input_dir):
    """
    Load ALL pairwise positive/negative files generated by
    01_split_by_zscore_direction.py.
    """

    print(f"INPUT DIR: {input_dir}")

    files = glob.glob(
        os.path.join(input_dir, "**", "*_positive.csv.gz"),
        recursive=True
    )

    files += glob.glob(
        os.path.join(input_dir, "**", "*_negative.csv.gz"),
        recursive=True
    )

    print(f"FOUND FILES: {len(files)}")

    dfs = []

    for f in files:

        print(f"Loading: {f}")

        filename = os.path.basename(f)

        # -------------------------------------------------
        # Determine direction
        # -------------------------------------------------

        if "_positive" in filename:
            direction = "Positive"
            trait_part = filename.replace("_positive.csv.gz", "")

        elif "_negative" in filename:
            direction = "Negative"
            trait_part = filename.replace("_negative.csv.gz", "")

        else:
            continue

        # -------------------------------------------------
        # Extract phenotypes from filename
        # -------------------------------------------------

        parts = trait_part.split("_")

        midpoint = len(parts) // 2

        phenotype1 = "_".join(parts[:midpoint])
        phenotype2 = "_".join(parts[midpoint:])

        # -------------------------------------------------
        # Load dataframe
        # -------------------------------------------------

        df = pd.read_csv(
            f,
            sep='\t',
            compression='gzip',
            low_memory=False
        )

        df["PairwiseDirection"] = direction
        df["Phenotype1"] = phenotype1
        df["Phenotype2"] = phenotype2

        dfs.append(df)

    if len(dfs) == 0:
        raise ValueError("No pairwise files found")

    merged = pd.concat(dfs, ignore_index=True)

    return merged

def detect_snp_column(df):
    """
    Automatically detect SNP column.
    Modify if necessary.
    """

    possible = ["SNP", "RSID", "rsID", "rsid"]

    for col in possible:
        if col in df.columns:
            return col

    raise ValueError(
        f"Could not detect SNP column. "
        f"Available columns: {list(df.columns)}"
    )


def classify_disease_snps(df, disease, snp_col):
    """
    Create disease-level SNP classifications.

    Rules:
    - Negative = SNP has >=1 negative pleiotropic comparison
    - Positive = all comparisons are positive
    """

    subset = df[
        (df["Phenotype1"] == disease) |
        (df["Phenotype2"] == disease)
    ].copy()

    if subset.empty:
        return pd.DataFrame()

    z_col = f"Z-{disease}"

    if z_col not in subset.columns:
        raise ValueError(f"Missing column: {z_col}")

    results = []

    for snp, snp_df in subset.groupby(snp_col):

        n_negative = (
            snp_df["PairwiseDirection"] == "Negative"
        ).sum()

        n_positive = (
            snp_df["PairwiseDirection"] == "Positive"
        ).sum()

        classification = (
            "Negative"
            if n_negative > 0
            else "Positive"
        )

        z_values = snp_df[z_col].dropna()

        if len(z_values) == 0:
            continue

        signed_z = z_values.iloc[0]
        abs_z = abs(signed_z)

        traits = set(
            snp_df["Phenotype1"].tolist() +
            snp_df["Phenotype2"].tolist()
        )

        traits.discard(disease)

        results.append({
            "SNP": snp,
            "Disease": disease,
            "signed_z": signed_z,
            "abs_z": abs_z,
            "n_positive_pairs": n_positive,
            "n_negative_pairs": n_negative,
            "n_total_pairs": n_positive + n_negative,
            "classification": classification,
            "compared_traits": ";".join(sorted(traits))
        })

    return pd.DataFrame(results)


def save_outputs(df, out_prefix):

    csv_path = f"{out_prefix}.csv.gz"

    df.to_csv(
        csv_path,
        sep='\t',
        index=False,
        compression='gzip'
    )

    print(f"Saved: {csv_path}")


# =========================================================
# MAIN
# =========================================================

input_dir = sys.argv[1].rstrip("/")
out_dir = sys.argv[2].rstrip("/")

os.makedirs(out_dir, exist_ok=True)

# ---------------------------------------------------------
# LOAD
# ---------------------------------------------------------

merged = load_pairwise_files(input_dir)

print(f"Merged rows: {len(merged)}")

# ---------------------------------------------------------
# REMOVE HDL / LDL COMPARISONS
# ---------------------------------------------------------

excluded_traits = {"HDL_t", "LDL_t"}

merged = merged[
    ~merged["Phenotype1"].isin(excluded_traits) &
    ~merged["Phenotype2"].isin(excluded_traits)
].copy()

print(
    f"Rows after HDL/LDL removal: {len(merged)}"
)

snp_col = detect_snp_column(merged)

print(f"Detected SNP column: {snp_col}")

# ---------------------------------------------------------
# DISEASE-SPECIFIC DATASETS
# ---------------------------------------------------------

all_disease_dfs = []

for disease in DISEASES:

    short = TRANSLATION[disease]

    print(f"\nProcessing disease: {disease}")

    disease_df = classify_disease_snps(
        merged,
        disease,
        snp_col
    )

    if disease_df.empty:
        print(f"No SNPs for {disease}")
        continue

    all_disease_dfs.append(disease_df)

    # -----------------------------------------------------
    # Positive
    # -----------------------------------------------------

    pos_df = disease_df[
        disease_df["classification"] == "Positive"
    ].copy()

    save_outputs(
        pos_df,
        os.path.join(out_dir, f"{short}_positive_snps_noChol")
    )

    # -----------------------------------------------------
    # Negative
    # -----------------------------------------------------

    neg_df = disease_df[
        disease_df["classification"] == "Negative"
    ].copy()

    save_outputs(
        neg_df,
        os.path.join(out_dir, f"{short}_negative_snps_noChol")
    )

# ---------------------------------------------------------
# GLOBAL DATASETS
# ---------------------------------------------------------

all_df = pd.concat(all_disease_dfs, ignore_index=True)

# ---------------------------------------------------------
# Global positive
# ---------------------------------------------------------

all_positive = all_df[
    all_df["classification"] == "Positive"
].copy()

save_outputs(
    all_positive,
    os.path.join(out_dir, "All_positive_snps_noChol")
)

# ---------------------------------------------------------
# Global negative
# ---------------------------------------------------------

all_negative = all_df[
    all_df["classification"] == "Negative"
].copy()

save_outputs(
    all_negative,
    os.path.join(out_dir, "All_negative_snps_noChol")
)

print("\nDONE")
